name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -trimpath -buildvcs=false -ldflags="-s -w" -v ./...
        GOOS: windows
        GOARCH: amd64

      - name: Test with the Go CLI
        run: go test
