name: Go
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install dependencies
        run: |
          go get .
          go install gioui.org/cmd/gogio@latest

      - name: Build
        run: gogio -target=windows -ldflags="-s -w" .

      - name: Test with the Go CLI
        run: go test